spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Daohao250=
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.hupan.springshiro.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2-spring.xml